// src/app/ui/dancing-letters/dancing-letters.component.ts
import { Component, Input, OnChanges } from "@angular/core";

@Component({
	selector: "app-dancing-letters",
	templateUrl: "./dancing-letters.component.html",
	styleUrls: ["./dancing-letters.component.scss"],
})
export class DancingLettersComponent implements OnChanges {
	@Input() text = "";

	letters: string[] = [];
	animating = false;

	constructor() {}

	ngOnChanges() {
		this.letters = this.text.split("");
		this.animating = false;
		setTimeout(() => {
			this.animating = true;
		}, 100);
	}
}

<span [class.letters]="animating">
	<span
		*ngFor="let letter of letters; let i = index"
		[style.animationDelay]="(letters.length - i) * -100 + 'ms'"
		[style.display]="letter == ' ' ? 'initial' : ''"
	>
		{{ letter }}
	</span>
</span>

// components/ui/DancingLetters.tsx
import { chakra } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import styles from "./DancingLetters.module.scss";

export default function DancingLetters(props: { children: string }) {
	const letters = props.children ?? "";

	const [enabled, setEnabled] = useState(true);

	useEffect(() => {
		setEnabled(false);
		setTimeout(() => {
			setEnabled(true);
		}, 100);
	}, [letters]);

	return (
		<>
			{letters.split("").map((letter, i) => (
				<chakra.span
					key={i}
					className={enabled ? styles.letter : ""}
					style={{
						animationDelay: (letters.length - i) * -100 + "ms",
						display: letter == " " ? "initial" : "",
					}}
				>
					{letter}
				</chakra.span>
			))}
		</>
	);
}
